### ISSUE TITLE
Remote I/O error when trying to use relay8 from file

### ISSUE THREAD

**Issue by N3jk0v** [SequentMicrosystems/8relay-rpi#1]
When I try to attempt to read or write data on the relay plate using relay8 import in a python file I always get Remote I/O error.
I can use the terminal to read/write data without an issue.

**Comment by alexburcea2877** [comment]
Hi, let me understand your problem, you open a issue on the "8relay" repository and you talk about "relay8" command.
First, you have 8relay board (the one with plug-gable connectors https://github.com/SequentMicrosystems/8relay-rpi) or the old version relay8 (the one with screw connectors  https://github.com/SequentMicrosystems/relay8-rpi).
Depend of your board you have to follow the instructions  from "README.md" file located on the "python" folder on the corresponding repository .

Sorry for the confusion we make with this  two similar boards but even if we do not produce 8relay board (screw connectors) we still have to support them.

Let me know what type of board you have and if the instructions are not clear.

**Comment by N3jk0v** [comment]
Thank you for the fast feedback. It indeed appears that i used 8relay commands for relay8 type module. I have now tesed it and it now works as intended.
Thanks!
