### ISSUE TITLE
Can not find module lib8relay. 

### ISSUE THREAD

**Issue by Jwizzswizz** [SequentMicrosystems/8relay-rpi#2]
I have installed this code several times I can get it to work for the command prompt when I run test. But when I try to code using python it comes up with nothing.  I'm running python 3 not 2.

Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
ModuleNotFoundError: No module named 'lib8relay'

**Comment by alexburcea2877** [comment]
Hi,

You have to install the python library, follow the install  instructions
form python subfolder:
https://github.com/SequentMicrosystems/8relay-rpi/blob/master/python/README.md

În lun., 20 iul. 2020 la 19:51, Jwizzswizz <notifications@github.com> a
scris:

**Comment by Jwizzswizz** [comment]
Hello,

I have everything install and it works just not with my interpreter. It only works in the python command line of my raspberry pi. I try to write code in thonny and it can't find the lib8relay function to work. When I run the code in thonny it can not find the library.  I want to have a program control the code and not have to run it on the command line in python. 



<img width="297" alt="github issue with 8-relay" src="https://user-images.githubusercontent.com/68550411/87982025-c742b200-ca9b-11ea-9db8-0ebd650a9054.PNG">

**Comment by alexburcea2877** [comment]
Tell me what version of python use thonny ?
If, as I expected, you use python3, you have to install the library for
python3 by replacing in install instructions "python" with "python3".
I see in your picture that you try to use the "8relay" command  in python,
which is wrong. There are 2 different things: "8relay"is a system command
which calls an executable program and the "lib8relay" is a  python library
which contains functions described in the README.md file located under the
"python" folder in the repository.


În lun., 20 iul. 2020 la 23:17, Jwizzswizz <notifications@github.com> a
scris:

**Comment by alexburcea2877** [comment]
Actualy only this line : "~/8relay-rpi/python/8relay$ sudo python setup.py
install"  become  "~/8relay-rpi/python/8relay$ sudo python3 setup.py
install"

**Comment by Jwizzswizz** [comment]
Perfect. It runs like a dream all I need to do was install with python3

**Comment by alexburcea2877** [comment]
Problem solved

**Comment by piehouserat** [comment]
ahhhhhh just discovered this after a frustrating hour, can you update the docs, etc?

EDIT: to be fair I've just started playing with python for this project so maybe this would be kinda obvious for a more experienced python dev...

**Comment by alexburcea2877** [comment]
Hi,

Sorry for the inconvenience and thank you for the suggestion.
We update de readme.md file under python folder:
https://github.com/SequentMicrosystems/8relay-rpi/blob/master/python/README.md

Thank you for supporting our products.

Alex.


În lun., 3 aug. 2020 la 14:56, Martin Tomaszczyk <notifications@github.com>
a scris:
