### ISSUE TITLE
Publish to PyPI?

### ISSUE THREAD

**Issue by virgilm** [SequentMicrosystems/8relay-rpi#4]
Would you push your package to PyPI please?

I am developing an integration for HA ([Homeassistant](https://www.home-assistant.io/integrations/)) and I need this package  uploaded to PyPI.

You can find the code (quite rough for now) here:
https://github.com/virgilm/raspipool/tree/master/custom_components/sequent_microsystems

If you are pushing this to HA, I can help developing it.

**Comment by alexburcea2877** [comment]
As soon as I find some time to search the web on how to do this, I will do
it.
Thank you for your suggestion.

Alex


În vin., 4 sept. 2020 la 21:02, virgilm <notifications@github.com> a scris:

**Comment by alexburcea2877** [comment]
The lib8relay is on PyPI. Can you point me more precise documentation about integrating 8Relay to HA?
