### ISSUE TITLE
Compute Module 3 Plus - Relay Board Not Found

### ISSUE THREAD

**Issue by mattylight22** [SequentMicrosystems/8relay-rpi#5]
I am trying to use the 8Relay board on a compute module 3+, after following the instructions carefully many times I am unable to detect the relay board.

I have tested the relay board on a RPI 3 & 4 and can confirm it does work on those devices.

When I run the command "8relay -list" on the compute module it gives me the message "0 board(s) detected"

**Comment by alexburcea2877** [comment]
Hi,

How do you connect the compute module with an 8-RELAY card, is it some
carrier board or something?
The idea is that the software we provide assumes that you connect the card
on the I2C-1 port of the Raspberry processor.
Please check-out the I2C port you use and change that port in the software
source code and reinstall the package.

Tell me if all above make sense to you (I am not native english speaker)
and if you have more questions.

Regards,
Alex

În vin., 30 oct. 2020 la 07:31, Matt Nick <notifications@github.com> a
scris:

**Comment by mattylight22** [comment]
Hello Alex,

This is the compute board I am using:
![image](https://user-images.githubusercontent.com/68877341/97787972-7c990180-1b83-11eb-815d-9839cf8274f7.png)

It has the same GPIO configuration as a Raspberry PI 4.

These are the read outs I see in the OS regarding I2C-1
![image](https://user-images.githubusercontent.com/68877341/97788025-a4886500-1b83-11eb-81f9-0d1f376f582c.png)

Do you see anything obvious that I am missing to make this work properly?

Thank You,
Matt

**Comment by alexburcea2877** [comment]
Hi Matt,

All looks ok on the software part, the i2c pins are at the correct
positions.
Can you check with a multimeter if the I2C line makes contact at the 40
pins connector?
If you power the 8Relay card from the compute board, check the +5V signal
at the 8Relay part .

Alex.


În sâm., 31 oct. 2020 la 21:17, Matt Nick <notifications@github.com> a
scris:

**Comment by mattylight22** [comment]
Thank you Alex, this particular compute board did not have built in pull-up resistors. It is working as described now.
