### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by kbooth06** [SequentMicrosystems/8relay-rpi#6]
I followed the installation instructions for the 8relay-rpi driver but I think I have an installation problem.  When running the test I get the following.  Very new to Raspberry and Python so not sure where to go from here.

Type "help", "copyright", "credits" or "license" for more information.
>>> import lib8relay
>>> lib8relay.get_all(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/lib8relay/__init__.py", line 138, in get_all
IOError: [Errno 2] No such file or directory

**Comment by alexburcea2877** [comment]
Hi, 
Sorry for the delayed response.
You forgot to enable the I2C interface, run "sudo raspi-config" and brows to the "Interface Options" menu and enable the I2C port.
The suggestion is made in the repository[ README.md](https://github.com/SequentMicrosystems/8relay-rpi)  
Thank you for patience,
Alex.

**Comment by kbooth06** [comment]
Thank you very much!!

**Comment by alexburcea2877** [comment]
Happy to help.
